library(here)

source(here('code', '0-simulate-data.R'))
source(here('code', '1.1-survey.R'))
source(here('code', '1.2-survey-attribute-specific.R'))
source(here('code', '2.1-explore-data.R'))
source(here('code', '3.1-model-mnl.R'))
source(here('code', '3.2-model-mnl-attribute-specific.R'))
source(here('code', '3.3-plot-model-mnl.R'))
source(here('code', '4.1-model-no_choice.R'))
source(here('code', '4.2-plot-no_choice.R'))
source(here('code', '5.1-uncertainty.R'))
source(here('code', '6.1-compute-wtp.R'))
source(here('code', '6.2-model-wtp.R'))
source(here('code', '6.3-plot-wtp.R'))
source(here('code', '7.1-compute-market-sims.R'))
source(here('code', '7.2-plot-market-sims.R'))
source(here('code', '8.1-model-mxl.R'))
source(here('code', '8.2-mnl-groups.R'))
source(here('code', '9.1-compute-sensitivity.R'))
source(here('code', '9.2-plot-sensitivity.R'))
